In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
import statsmodels.api as sm

In [2]:
#%% For graphs
import matplotlib.style as style
plt.rcParams.update({'axes.labelsize':16})
plt.rcParams.update({'axes.titlesize':16})
plt.rcParams.update({'legend.fontsize':16})
plt.rcParams['xtick.labelsize'] = 16
plt.rcParams['ytick.labelsize'] = 16
plt.rcParams['lines.linewidth'] = 4
style.use('ggplot')

In [3]:
'''Get data and put in adequate form'''
data = pd.read_csv('wdbc.csv', header=None).iloc[:, 1:12]
X = data.iloc[: , 1:]
X = np.array(X)
y = data.iloc[: , 0]
y = np.where(y == 'M', 1, 0)
y = np.array(y)

In [4]:
from GLM import GLM

In [5]:
#%% Fit with newton rapson
model2 = GLM(X,y)
model2.newton_rapson()
beta_newton = model2.beta

Converged in: 9 iterations


In [6]:
#%%compare with built-in Python function
logit = sm.Logit(y, model2.X).fit()
beta_function = logit.params #parameters

Optimization terminated successfully.
         Current function value: 0.128410
         Iterations 10


In [7]:
beta_function

array([ 0.48701675, -7.21550165,  1.65330142, -1.73610268, 13.99253365,
        1.07400828, -0.07716665,  0.67452961,  2.59059481,  0.445864  ,
       -0.48206004])

In [8]:
beta_newton

array([ 0.48701061, -7.21541179,  1.65329751, -1.73613703, 13.99245835,
        1.07400542, -0.0771663 ,  0.67452938,  2.59058965,  0.44586259,
       -0.48205781])

In [9]:
'''Get diagonal elements of inverted hessian at MLE'''
hessian = model2.hessian(beta_newton)#get Hessian at MLE
hessian_inv = np.linalg.inv(hessian)
diag_MLE = np.diag(-hessian_inv)
sd_MLE = np.sqrt(diag_MLE)
#compare with built-in function
sd_function=logit.bse

In [10]:
sd_MLE

array([ 0.56431907, 13.08341198,  0.2773306 , 12.26418379,  5.88571406,
        0.44902239,  1.0733976 ,  0.64675795,  1.10603559,  0.2911734 ,
        0.60352925])

In [11]:
sd_function

array([ 0.56432009, 13.08343372,  0.27733124, 12.26420078,  5.88572546,
        0.44902301,  1.07339889,  0.64675856,  1.10603714,  0.29117369,
        0.60353007])